"""
Event classes for event-driven backtest engine.

All events are timestamped and ordered chronologically.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, Optional, Any


class EventType(Enum):
    """Types of backtest events."""
    MARKET = "market"      # Market data update
    SIGNAL = "signal"      # Trading signal generated
    ORDER = "order"        # Order placed
    FILL = "fill"          # Order filled
    RISK = "risk"          # Risk limit breach
    REBALANCE = "rebalance"  # Portfolio rebalancing


@dataclass
class Event:
    """
    Base class for all events.

    All events must have a timestamp for proper ordering.
    """
    event_type: EventType
    timestamp: datetime

    def __lt__(self, other: 'Event') -> bool:
        """Compare events by timestamp for sorting."""
        return self.timestamp < other.timestamp

    def __repr__(self) -> str:
        """String representation."""
        return f"{self.event_type.value}@{self.timestamp}"


@dataclass
class MarketEvent(Event):
    """
    Market data update event.

    Triggered at start of each trading day with latest data.

    Attributes:
        data: Market data for this timestamp
    """
    data: Dict[str, Any] = field(default_factory=dict)

    def __init__(self, timestamp: datetime, data: Dict[str, Any]) -> None:
        """Initialize market event."""
        super().__init__(event_type=EventType.MARKET, timestamp=timestamp)
        self.data = data


@dataclass
class SignalEvent(Event):
    """
    Trading signal event.

    Generated by strategy, will be executed on NEXT trading day.

    Attributes:
        symbol: Stock symbol
        signal_type: 'LONG', 'SHORT', 'EXIT'
        strength: Signal strength (0.0 to 1.0)
        metadata: Additional signal information
    """
    symbol: str
    signal_type: str  # 'LONG', 'SHORT', 'EXIT'
    strength: float = 1.0  # 0.0 to 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __init__(
        self,
        timestamp: datetime,
        symbol: str,
        signal_type: str,
        strength: float = 1.0,
        metadata: Optional[Dict[str, Any]] = None
    ) -> None:
        """Initialize signal event."""
        super().__init__(event_type=EventType.SIGNAL, timestamp=timestamp)
        self.symbol = symbol
        self.signal_type = signal_type
        self.strength = max(0.0, min(1.0, strength))  # Clamp to [0, 1]
        self.metadata = metadata or {}


@dataclass
class OrderEvent(Event):
    """
    Order placement event.

    Represents an order to be executed.

    Attributes:
        symbol: Stock symbol
        order_type: 'MARKET', 'LIMIT', 'STOP'
        quantity: Number of shares (positive=buy, negative=sell)
        direction: 'BUY' or 'SELL'
        price: Limit/stop price (for non-market orders)
        metadata: Additional order information
    """
    symbol: str
    order_type: str  # 'MARKET', 'LIMIT', 'STOP'
    quantity: float
    direction: str  # 'BUY' or 'SELL'
    price: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __init__(
        self,
        timestamp: datetime,
        symbol: str,
        order_type: str,
        quantity: float,
        direction: str,
        price: Optional[float] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> None:
        """Initialize order event."""
        super().__init__(event_type=EventType.ORDER, timestamp=timestamp)
        self.symbol = symbol
        self.order_type = order_type
        self.quantity = abs(quantity)  # Always positive
        self.direction = direction
        self.price = price
        self.metadata = metadata or {}


@dataclass
class FillEvent(Event):
    """
    Order fill event.

    Represents completed order execution.

    Attributes:
        symbol: Stock symbol
        quantity: Number of shares filled
        fill_price: Execution price
        commission: Commission paid
        slippage: Slippage incurred
        direction: 'BUY' or 'SELL'
        metadata: Additional fill information
    """
    symbol: str
    quantity: float
    fill_price: float
    commission: float
    slippage: float
    direction: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __init__(
        self,
        timestamp: datetime,
        symbol: str,
        quantity: float,
        fill_price: float,
        commission: float,
        slippage: float,
        direction: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> None:
        """Initialize fill event."""
        super().__init__(event_type=EventType.FILL, timestamp=timestamp)
        self.symbol = symbol
        self.quantity = abs(quantity)
        self.fill_price = fill_price
        self.commission = commission
        self.slippage = slippage
        self.direction = direction
        self.metadata = metadata or {}

    @property
    def total_cost(self) -> float:
        """Calculate total cost including commission and slippage."""
        base_cost = self.quantity * self.fill_price
        return base_cost + self.commission + self.slippage


@dataclass
class RiskEvent(Event):
    """
    Risk limit breach event.

    Triggered when risk limits are violated.

    Attributes:
        risk_type: Type of risk limit breached
        severity: 'WARNING', 'ERROR', 'CRITICAL'
        message: Description of the breach
        data: Additional risk data
    """
    risk_type: str
    severity: str
    message: str
    data: Dict[str, Any] = field(default_factory=dict)

    def __init__(
        self,
        timestamp: datetime,
        risk_type: str,
        severity: str,
        message: str,
        data: Optional[Dict[str, Any]] = None
    ) -> None:
        """Initialize risk event."""
        super().__init__(event_type=EventType.RISK, timestamp=timestamp)
        self.risk_type = risk_type
        self.severity = severity
        self.message = message
        self.data = data or {}


@dataclass
class RebalanceEvent(Event):
    """
    Portfolio rebalancing event.

    Triggered when portfolio needs rebalancing.

    Attributes:
        reason: Reason for rebalancing
        target_weights: Target portfolio weights
        metadata: Additional rebalancing data
    """
    reason: str
    target_weights: Dict[str, float]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __init__(
        self,
        timestamp: datetime,
        reason: str,
        target_weights: Dict[str, float],
        metadata: Optional[Dict[str, Any]] = None
    ) -> None:
        """Initialize rebalance event."""
        super().__init__(event_type=EventType.REBALANCE, timestamp=timestamp)
        self.reason = reason
        self.target_weights = target_weights
        self.metadata = metadata or {}
